<a href="https://colab.research.google.com/github/radhikab662/SoC-2k21/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
my_list=[1,2,3]
import numpy as np
arr=np.array(my_list)
arr

array([1, 2, 3])

In [ ]:
my_list=[[1,2,3],[4,5,6],[7,8,9]]
np.array(my_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(0,10,3) #arange(start, stop, step size)

array([0, 3, 6, 9])

In [ ]:
np.zeros(3)  #return array of zeroes
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((3,4)) #returns array of ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.linspace(0,5,10) #returns 10 evenly spaced numbers between 0 and 5

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [ ]:
#creating identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#array of random numbers:
np.random.rand(5) #random array of numbers between 0 and 1

array([0.47516892, 0.49004592, 0.11399984, 0.9996097 , 0.82787941])

In [ ]:
np.random.rand(5,5) #returns 5 x 5 matrix

array([[0.94216523, 0.2244765 , 0.0032639 , 0.63530573, 0.20561805],
       [0.2744286 , 0.26499296, 0.91288387, 0.02973972, 0.8187235 ],
       [0.15619074, 0.15903158, 0.17798796, 0.23610846, 0.58948931],
       [0.53096569, 0.20292777, 0.14360361, 0.46131187, 0.56017748],
       [0.26511985, 0.75676603, 0.08451975, 0.87637528, 0.39350553]])

In [ ]:
np.random.randn(2) #returns 2 random numbers from a distribution (Gaussian?) centered around 0

array([-0.77949098,  1.15706367])

In [ ]:
np.random.randint(1,100) #returns a random integer

21

In [ ]:
randarr=np.random.randint(1,100,10) #returns 10 integers between 1 and 100 (in array form)
randarr

array([46, 30, 28, 91, 75, 57, 80, 30, 61, 30])

In [ ]:
arr= np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr.reshape(5,5) 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
#to find max/ min numbers
randarr.max() #similar for min

91

In [ ]:
randarr.argmax() #returns index of max no
#argmin() for index of min value

3

In [ ]:
randarr.shape #returns the dimensions.. in this eg it was a 1d array

(10,)

In [ ]:
randarr.dtype #returns data type of arrays

dtype('int64')

In [ ]:
from numpy.random import randint #could use this instead of np.random.randint(...)
randint(2,10)

2

NumPy Indexing and Selection


In [ ]:
import numpy as np
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[8] #returns value at index 8

8

In [ ]:
arr[1:5] #sliced notation, returns numbers from index 1 to 4

array([1, 2, 3, 4])

In [ ]:
arr[:6] #everything upto index 5

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr[5:] #start from index 5 till end of array

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
arr[0:5]=100 #broadcasts 100 as the value at these indices.
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [ ]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
slice_of_arr= arr[0:6]
slice_of_arr[:]=99 #setting all elements to 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [ ]:
arr #but this sets the original elements to 99 as well, which means numpy doesn't automatically set copies of arrays

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [ ]:
#to get a copy instead of a reference to the actual array,
arr_copy=arr.copy()
arr_copy[:]=100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [ ]:
arr #the original array remains unchanged in this case

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [ ]:
#to select elements from a 2d array:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
arr_2d[0][0] #double bracket notation

5

In [ ]:
arr_2d[0] #returns the whole row 0

array([ 5, 10, 15])

In [ ]:
arr_2d[1,2] #single bracket, comma notation

30

In [ ]:
#to get submatrices
arr_2d[:2,1:] #grab everything till (not including) row 2, everything from column 1  

array([[10, 15],
       [25, 30]])

In [ ]:
arr=np.arange(1,11)
bool_arr=arr > 5 #returns an array of boolean values
arr[bool_arr] #can use the boolean array to return the values where this condition was true

array([ 6,  7,  8,  9, 10])

In [ ]:
arr[arr>5] #in 1 step #IMP

array([ 6,  7,  8,  9, 10])

NumPy Operations

In [ ]:
import numpy as np
arr= np.arange(0,11)
arr + arr #adds 2 arrays on an element to element basis
#similarly, arr-arr, arr * arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
arr+100
#adds 100 to each element, similar for sub, multiplication

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [ ]:
arr/arr
#You get warned for 0/0 div, but it still executes

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
arr ** 2 #exponent

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [ ]:
np.sqrt(arr) #finds square root of each element

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [ ]:
np.max(arr) #could also write arr.max()

10

In [ ]:
np.sin(arr) #sin of each

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])